#!/usr/bin/env python2


import argparse
from lbt import __description__
from lbt import MainApp


if __name__ == "__main__":

    parser = argparse.ArgumentParser(description=__description__)

    parser.add_argument("-m", "--make_makefile", default=".lbt", 
                        help = "Generate makefile from specified json file")

    args = parser.parse_args()

    MainApp(args)
